- addon/adapters/cloud-firestore.js
- tests/unit/adapters/cloud-firestore-test.js
This fixes a bug where we can't fetch any relationship when the app is built under a production environment
> Fix relationship fetch bug on a prod environment

- .eslintrc.js
- addon/adapters/cloud-firestore.js
- addon/instance-initializers/cloud-firestore.js
- tests/dummy/app/controllers/mirage.js
- tests/unit/instance-initializers/cloud-firestore-test.js
Moving `tracker` declaration inside `init()` caused some bugs. This PR reverts that changes. We use immutability to avoid leaking object states.
> Fix regression caused by assigning arrays and objects inside init()

- addon-test-support/index.js
- addon-test-support/mocks/cloud-firestore.js
- package-lock.json
- package.json
Exposes a [mock-cloud-firestore](https://github.com/rmmmp/mock-cloud-firestore) test helper.
Docs will come soon once I've plotted out a migration away from Mirage.
> Add mock-cloud-firestore test helper

- addon/serializers/cloud-firestore.js
This fixes an issue where the `hasMany` relationship are being included in the payload when saving a record. `hasMany` relationships should be saved manually by [batching](https://github.com/rmmmp/ember-cloud-firestore-adapter/blob/master/guides/04-creating-updating-deleting-records.md#batched-writes) it.
> Fix relationship bug

- addon/adapters/cloud-firestore.js
- addon/serializers/cloud-firestore.js
- addon/services/firestore.js
- app/services/firestore.js
- tests/unit/adapters/cloud-firestore-test.js
- tests/unit/services/firestore-test.js
I made the `firestore` instance a singleton on a newly created `firestore` service.
When asked for the instance I will also set the right settings getting rid of the deprecation warning in #43
> Makes firestore a singleton and sets correct timestamp setting

- addon/adapters/cloud-firestore.js
- tests/unit/adapters/cloud-firestore-test.js
This change forces an `attr('timestamp')` to be a `new Date()` locally.
When you have `isRealtime: true`, the server timestamp will sync by
itself overwriting the local date.
> Force timestamp to be a Date locally

- .eslintrc.js
- addon/authenticators/firebase.js
- addon/session-stores/firebase.js
- app/session-stores/firebase.js
- fastboot/initializers/firebase.js
- guides/07-authentication.md
- index.js
- lib/config.js
- package-lock.json
- package.json
- service-worker/index.js
- tests/unit/authenticators/firebase-test.js
- tests/unit/session-stores/firebase-test.js
- vendor/fastboot/firebase-auth.js
- vendor/fastboot/firebase-firestore.js
> Add support for FastBoot authentication

- index.js
- package-lock.json
- package.json
- tests/dummy/config/environment.js
This PR updates `ember-firebase-service` to `v8.0.0`. This is considered a breaking change as the addon will now leverage the FastBoot friendly `firebase-<product>.js` modules provided for free by `ember-firebase-service`. Since these files didn't exist before, using `ember-firebase-service` below `v8.0.0` will prevent this addon from working.
> Update ember-firebase-service to v8.0.0

- .github/FUNDING.yml
- README.md
- docs/authentication.md
- docs/create-update-delete-records.md
- docs/data-structure.md
- docs/finding-records.md
- docs/getting-started.md
- docs/relationships.md
- docs/testing.md
- docs/transforms.md
As we slowly move towards the `1.0.0` goals, it will be very important to have a docs system with versioning. Our current docs site doesn't have this right now. While the long term goal is to make use of a good static site generator out there, it's not in my priority to look into it right now so a simple markdown docs in this repository will do.
With a simple markdown docs, we get versioning for free as well.
I've also took the time to update the docs with the latest Ember syntax as well as having guides for using the Firebase Emulator.
> Create markdown docs

- addon/adapters/cloud-firestore.ts
- addon/serializers/cloud-firestore.ts
- docs/relationships.md
- tests/acceptance/features-test.ts
- tests/dummy/app/controllers/features.ts
- tests/dummy/app/models/post.ts
- tests/dummy/app/templates/features.hbs
- tests/unit/adapters/cloud-firestore-test.ts
> Support buildReference for one-to-many relationships

- addon/instance-initializers/firebase-settings.ts
- docs/getting-started.md
- docs/testing.md
- tests/dummy/config/environment.js
This adds (optional) support for the firebase auth service emulator. Currently ember-cloud-firestore-adapter seems to support the firestore emulator, and supports auth using the live service, but afaict the auth emulator isn't supported. 
The name of the firestore emulator port is changed to `firestorePort` for consistency, but the existing name (`port`) is still supported for backwards compatibility
> Support the Firebase auth service emulator

- docs/getting-started.md
- docs/testing.md
I missed a bug in #184. We just need to overwrite key `emulator` and not the whole object.
> Fix README (😅)

- addon/-private/flatten-doc-snapshot.ts
- addon/-private/realtime-tracker-modular.ts
- addon/adapters/cloud-firestore-modular.ts
- addon/serializers/cloud-firestore-modular.ts
- app/adapters/cloud-firestore-modular.js
- app/serializers/cloud-firestore-modular.js
- docs/authentication.md
- docs/create-update-delete-records.md
- docs/finding-records.md
- docs/getting-started.md
- docs/relationships.md
- docs/transforms.md
- tests/dummy/app/adapters/application.ts
- tests/dummy/app/controllers/features.ts
- tests/dummy/app/models/group.ts
- tests/dummy/app/models/post.ts
- tests/dummy/app/serializers/application.ts
- tests/unit/-private/realtime-tracker-modular-test.ts
- tests/unit/-private/realtime-tracker-test.ts
- tests/unit/adapters/cloud-firestore-modular-test.ts
- tests/unit/serializers/cloud-firestore-modular-test.ts
Part of #178 
This change introduces the `cloud-firestore-modular` adapter and serializer which makes uses of the Firestore Modular SDK. Originally, it was planned to avoid creating a new module as we could've combined Compat and Modular SDK code style as shown [here](https://firebase.google.com/docs/web/modular-upgrade#example_3_combining_version_8_and_version_9_code_styles). But the support for it is poor and not everything is compatible.
e.g.
```javascript
import { writeBatch } from 'firebase/firestore';
...
const docRef = db.collection('users').doc('user_a');
const batch = writeBatch(db);
batch.set(docRef, { name: 'Foo' }); // <-- invalid because docRef uses compat SDK
```
So instead, it's now ending up to be an all-in transition towards Modular SDK and the Compat SDK adapter and …
> Support Firestore Modular SDK through new Adapter and Serializer

- tests/acceptance/features-test.ts
- tests/unit/-private/build-collection-name-test.ts
- tests/unit/-private/realtime-tracker-modular-test.ts
- tests/unit/-private/realtime-tracker-test.ts
- tests/unit/adapters/cloud-firestore-modular-test.ts
- tests/unit/adapters/cloud-firestore-test.ts
- tests/unit/authenticators/firebase-test.ts
- Convert QUnit `equal` invocations to `strictEqual` (required in Ember 4's QUnit version)
- Cast numbers to strings in two tests
> [Redo] QUnit `equal` -> `strictEqual`

- addon/adapters/cloud-firestore-modular.ts
- addon/services/-firestore-data-manager.ts
- package.json
- tests/dummy/app/routes/find-record.ts
- tests/dummy/app/routes/query.ts
- tests/unit/services/-firestore-data-manager-test.ts
Recent discoveries from #242 specifically in this [comment](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/issues/242#issuecomment-1061535783) has shown that there's a cache bug in the addon.
e.g.
```javascript
store.findRecord('user', 'user_a', {
adapterOptions: { isRealtime: true },
});
// Somewhere down the line
store.findAll('user');
```
What will happen here is `store.findAll` won't return all user data because `isRealtime` isn't set to `true`. Behind the scenes, this still do a `onSnapshot` that quickly unsubscribes because we want to utilize the caching mechanism of Firestore. Unfortunately, because we unsubscribe immediately, we only really return the cached data which is what was returned from the previous `store.findRecord`. This is also an issue with `hasMany` …
> Fix cache bug

- addon/serializers/cloud-firestore-modular.ts
- docs/relationships.md
**Changes:**
- Expose snapshot record to `buildReference` of a `belongsTo` relationship
- Fix doc not indicating that snapshot record is exposed for `buildReference` of a `hasMany` relationship
> Expose snapshot record to belongsTo buildReference

- tests/unit/adapters/cloud-firestore-modular-test.ts
Passes actual `Store` objects in tests instead of `{}`. Left unchanged these lines will become TS errors when EmberData TS types are updated.
> chore: pass `Store` service objects in tests

- addon/adapters/cloud-firestore-modular.ts
- addon/serializers/cloud-firestore-modular.ts
- Update serializer `extractRelationships` method to use `ModelSchema` and `{ determineRelationshipType(descriptor: { kind: string, type: string }, store: Store): string; }` intersection type
- Expose some adapter types and properties to make subclassing easier
> chore: fix serializer `extractRelationships` types, expose adapter properties

- addon/adapters/cloud-firestore-modular.ts
https://deprecations.emberjs.com/ember-data/v4.x/#toc_ember-data-deprecate-snapshot-model-class-access
> fix: remove `snapshot.type` usage to fix `ember-data:deprecate-snapshot-model-class-access` deprecation

- tests/unit/serializers/cloud-firestore-modular-test.ts
- Adds test to `CloudFirestoreSerializer` to ensure model relationship links are extracted
> feat: add test for serializer `extractRelationships` method

- ember-cli-build.js
- package-lock.json
- package.json
- Support `ember-simple-auth` v6 in `peerDependencies`
- Remove unused build setting that opts out of ESA initializer
> chore: support `ember-simple-auth` v6

- addon/adapters/cloud-firestore-modular.ts
- addon/utils/custom-errors.ts
- docs/finding-records.md
- tests/unit/adapters/cloud-firestore-modular-test.ts
- tests/unit/utils/custom-errors-test.ts
Fixes #305 
This is a breaking change.
I opted to export `AdapterRecordNotFoundError` as default instead of modifying the generated re-export files in `app` . `custom-errors` only contains one export currently.
> fix!: export `AdapterRecordNotFoundError` as default

- ember-cli-build.js
- package-lock.json
- package.json
Fixes error that occurs after `ember-data` update:
```
Global error: Uncaught Error: Could not find module `@ember/polyfills` imported from `ember-simple-auth/utils/assign`
```
Also updates `@embroider/test-setup` to fix Embroider errors related to `ember-cookies`:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-cookies/services/cookies'
```
> chore: update `ember-simple-auth` in test app

- package.json
- Fixes FastBoot error in test app
- First occurred after EmberData update
> fix: add crypto to `fastbootDependencies`

- tests/dummy/app/controllers/features.ts
```
DEPRECATION: The EmberObject get method on the class RecordArray is deprecated. Use dot-notation javascript get/set access instead. [deprecation id: ember-data:deprecate-array-like] This will be removed in ember-data 5.0.
DEPRECATION: The `firstObject` method on the class RecordArray is deprecated. Use the native array method `[0]` instead. [deprecation id: ember-data:deprecate-array-like] This will be removed in ember-data 5.0.
```
> Fix array proxy deprecation

- addon/adapters/cloud-firestore-modular.ts
- package.json
- tests/dummy/app/models/user.ts
- tests/unit/adapters/cloud-firestore-modular-test.ts
- Export rest of internal adapter types (these are needed when overriding adapter in host app)
- Use real `modelFor` and `_createSnapshot` fns instead of plain objects in adapter test
> chore: export adapter types, fix adapter test arrangements
