mikkopaderes/ember-cloud-firestore-adapter

addon/adapters/cloud-firestore.js
tests/dummy/app/controllers/query.js
tests/dummy/app/routes/query.js
tests/helpers/fixture-data.js
tests/unit/adapters/cloud-firestore-test.js

Implement new API for findRecord() and query()

---

addon-test-support/mocks/cloud-firestore.js
addon/adapters/cloud-firestore.js
package-lock.json
package.json
tests/dummy/app/models/group.js
tests/helpers/fixture-data.js
tests/unit/adapters/cloud-firestore-test.js

Implement hasMany filtering

---

index.js
package-lock.json
package.json
vendor/fastboot/firestore.js

Fix fastboot

---

package-lock.json
package.json

Fixes fastboot bug during deployment to server

Fix fastboot bug

---

.travis.yml
addon/adapters/cloud-firestore.js
guides/04-creating-updating-deleting-records.md
guides/06-relationships.md
tests/dummy/app/models/user.js
tests/helpers/fixture-data.js
tests/unit/adapters/cloud-firestore-test.js

Add record in hasMany buildReference hook

---

addon/transforms/timestamp.js
package-lock.json
package.json
tests/dummy/app/templates/components/group-posts.hbs
tests/unit/transforms/timestamp-test.js

Fix deprecation for timestamp transform

---

README.md
guides/02-configuration.md
package-lock.json
package.json

This will also update Firebase to 5.x

Update ember-firebase-service to v5.0.0

---

addon/adapters/cloud-firestore.js
addon/utils/realtime-tracker.js
guides/03-finding-records.md
guides/06-relationships.md
tests/dummy/app/adapters/application.js
tests/helpers/fixture-data.js
tests/unit/adapters/cloud-firestore-test.js
tests/unit/utils/realtime-tracker-test.js

Allow sub-collection fetching

---

addon/adapters/cloud-firestore.js

Change default Firestore settings

---

addon/utils/realtime-tracker.js
tests/unit/utils/realtime-tracker-test.js

This fixes an issue where updating a query/has-many wouldn't show the
new records

Fix query not reflecting new records on update

---

.travis.yml
addon/adapters/cloud-firestore.js
addon/utils/realtime-tracker.js
config/ember-try.js
tests/unit/utils/realtime-tracker-test.js

This fixes an issue where a realtime fetch would set the record in the store twice on initial load.

Fix duplicate cache push

---

addon/adapters/cloud-firestore.js
package-lock.json
package.json

Disable realtime listeners in FastBoot

---

addon/transforms/timestamp.ts
docs/transforms.md
tests/unit/transforms/timestamp-test.ts

Fix timestamp serialization

---

addon/-private/build-collection-name.ts
addon/adapters/cloud-firestore.ts
tests/acceptance/features-test.ts
tests/dummy/app/controllers/features.ts
tests/dummy/app/templates/features.hbs
tests/unit/adapters/cloud-firestore-test.ts

Fix creating records without IDs not working

---

.gitignore
addon/serializers/cloud-firestore.ts
tests/acceptance/features-test.ts
tests/dummy/app/controllers/features.ts
tests/dummy/app/templates/features.hbs

Fix belongs to serialization bug

---

docs/getting-started.md

Add serializer section in docs

---

service-worker/index.js

Fix service worker not using compat SDK

---

tests/dummy/app/models/user.ts

- Removed unused `users` reflexive hasMany relationship in dummy app

Removed unused hasMany

---

tests/dummy/app/controllers/query.ts
tests/dummy/app/routes/query.ts

[Redo] Fix dummy modular format

---

addon/-private/realtime-tracker-modular.ts
addon/-private/realtime-tracker.ts
tests/dummy/app/controllers/application.ts

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

Replace deprecated `substr` functions with `substring`

---

addon/adapters/cloud-firestore-modular.ts
addon/adapters/cloud-firestore.ts
addon/utils/custom-errors.ts
app/utils/custom-errors.js
docs/finding-records.md
tests/unit/adapters/cloud-firestore-modular-test.ts
tests/unit/utils/custom-errors-test.ts

Resolves #159 
Only `AdapterRecordNotFoundError` at the moment

Support custom error

---

addon/services/-firestore-data-manager.ts

Fix potential race condition for realtime queries

---

addon/instance-initializers/firebase-settings.ts
scripts/build-wrappers.ts

Fixes #273. Not sure how to generate the functions/storage imports

Add functions, storage emulator setup to initializer

---

addon/services/-firestore-data-manager.ts

Fix race condition when loading data

---

package-lock.json
package.json

https://github.com/cevek/ttypescript/issues/150

chore: update `ttypescript`

---

package-lock.json
package.json

Fixes `TypeError: The comparison function must be either a function or undefined`

chore: update `ember-cli-fastboot` to v4

---

package-lock.json
package.json

- Allow `firebase` v10 in peer
- Update `firebase` to v10 in test app

feat: support `firebase` v10
